export type ServerMovie = {
  id: number;
  emojis: string;
  answers: string[];
};

export const serverMovies: ServerMovie[] = [
  { id: 0, emojis: "🦁👑", answers: ["Le Roi Lion", "Roi Lion"] },
  { id: 1, emojis: "🧊❄️👸", answers: ["La Reine des Neiges"] },
  { id: 2, emojis: "🦈", answers: ["Les Dents de la Mer"] },
  { id: 3, emojis: "🚢💑🧊", answers: ["Titanic"] },
  { id: 4, emojis: "🧙‍♂️💍🌋", answers: ["Le Seigneur des Anneaux"] },
  { id: 5, emojis: "👽🚲🌕", answers: ["E.T.", "E.T. l'extra-terrestre"] },
  { id: 6, emojis: "🤖❤️🌱", answers: ["Wall-E", "WALL-E"] },
  { id: 7, emojis: "🐀👨‍🍳🇫🇷", answers: ["Ratatouille"] },
  { id: 8, emojis: "🕷️🧑", answers: ["Spider-Man", "Spiderman"] },
  { id: 9, emojis: "🧹✨👦🏰", answers: ["Harry Potter", "Harry Potter à l'école des sorciers"] },
  { id: 10, emojis: "🏴‍☠️🚢⚓", answers: ["Pirates des Caraïbes", "Pirate des Caraïbes"] },
  { id: 11, emojis: "🦇🌃", answers: ["Batman"] },
  { id: 12, emojis: "👸🐸💋", answers: ["La Princesse et la Grenouille"] },
  { id: 13, emojis: "🏎️⚡", answers: ["Cars"] },
  { id: 14, emojis: "🎈🏠👴", answers: ["Là-Haut"] },
  { id: 15, emojis: "⭐🔫🌌", answers: ["Star Wars", "La Guerre des Étoiles"] },
  { id: 16, emojis: "🦖🏝️", answers: ["Jurassic Park"] },
  { id: 17, emojis: "👻👨‍🔬🚫", answers: ["SOS Fantômes"] },
  { id: 18, emojis: "🎭😈👨‍⚖️", answers: ["Joker"] },
  { id: 19, emojis: "🧊💎🚢🔫", answers: ["James Bond", "007"] },
  { id: 20, emojis: "🥊🇮🇹🥇", answers: ["Rocky"] },
  { id: 21, emojis: "🌊🏄‍♂️🦈", answers: ["Point Break", "Extrême Limite"] },
  { id: 22, emojis: "💊🔴🔵🕶️", answers: ["Matrix"] },
  { id: 23, emojis: "🦍🏙️✈️", answers: ["King Kong"] },
  { id: 24, emojis: "🔪🚿😱", answers: ["Psychose"] },
  { id: 25, emojis: "👧📼📺👻", answers: ["Le Cercle", "Ring"] },
  { id: 26, emojis: "🧟‍♂️🛒🇬🇧", answers: ["Shaun of the Dead"] },
  { id: 27, emojis: "🎪🐘✨", answers: ["Dumbo"] },
  { id: 28, emojis: "🧜‍♀️🐚🌊", answers: ["La Petite Sirène"] },
  { id: 29, emojis: "🐕🛷❄️", answers: ["Croc-Blanc"] },
  { id: 30, emojis: "🧸🐷🐯🌳", answers: ["Winnie l'Ourson"] },
  { id: 31, emojis: "🏺⚡🦸", answers: ["Hercule"] },
  { id: 32, emojis: "🐒🌴📖👦", answers: ["Le Livre de la Jungle"] },
  { id: 33, emojis: "🧞‍♂️🏜️🕌", answers: ["Aladdin"] },
  { id: 34, emojis: "👸🍎😴", answers: ["Blanche-Neige", "Blanche Neige"] },
  { id: 35, emojis: "💃🌹🏰🧌", answers: ["La Belle et la Bête"] },
  { id: 36, emojis: "🎃🎄💀", answers: ["L'Étrange Noël de Monsieur Jack"] },
  { id: 37, emojis: "👨‍🚀🌕🚀", answers: ["Apollo 13"] },
  { id: 38, emojis: "🤖👦🔫🌋", answers: ["Terminator"] },
  { id: 39, emojis: "🐉🗡️🧒", answers: ["Dragons"] },
  { id: 40, emojis: "🟢👹🏰", answers: ["Shrek"] },
  { id: 41, emojis: "🐧❄️🎤", answers: ["Happy Feet"] },
  { id: 42, emojis: "🐠🔍👨‍👦", answers: ["Le Monde de Nemo", "Nemo"] },
  { id: 43, emojis: "🐙🐠💙", answers: ["Le Monde de Dory", "Dory"] },
  { id: 44, emojis: "🧸🤠🚀", answers: ["Toy Story"] },
  { id: 45, emojis: "🦸‍♂️👨‍👩‍👧‍👦🦹", answers: ["Les Indestructibles"] },
  { id: 46, emojis: "🐜🌿👑", answers: ["1001 Pattes", "Fourmiz"] },
  { id: 47, emojis: "👹👧🚪", answers: ["Monstres et Cie", "Monstres & Cie"] },
  { id: 48, emojis: "🦊🐰🔍🏙️", answers: ["Zootopie"] },
  { id: 49, emojis: "🌊🧭🏝️🐓", answers: ["Vaiana"] },
  { id: 50, emojis: "🦸‍♂️🔨⚡", answers: ["Thor"] },
  { id: 51, emojis: "🧪💪🟢", answers: ["Hulk", "L'Incroyable Hulk"] },
  { id: 52, emojis: "🛡️⭐🇺🇸", answers: ["Captain America"] },
  { id: 53, emojis: "🤖❤️🦸‍♂️", answers: ["Iron Man"] },
  { id: 54, emojis: "🐜🦸‍♂️", answers: ["Ant-Man"] },
  { id: 55, emojis: "🕷️🌌✨🕷️", answers: ["Spider-Man: New Generation"] },
  { id: 56, emojis: "💎🟣✊🦹", answers: ["Avengers", "Avengers: Infinity War"] },
  { id: 57, emojis: "🌍🐒🔬", answers: ["La Planète des Singes"] },
  { id: 58, emojis: "🚁🔫💪🇻🇳", answers: ["Rambo"] },
  { id: 59, emojis: "🎰🃏🍸", answers: ["Casino Royale"] },
  { id: 60, emojis: "🏎️🔥💨", answers: ["Fast and Furious", "Fast & Furious"] },
  { id: 61, emojis: "👨‍✈️🛫🌊🏝️", answers: ["Seul au Monde"] },
  { id: 62, emojis: "🎹🎻🌹👻", answers: ["Le Fantôme de l'Opéra"] },
  { id: 63, emojis: "🧛🦇🏰", answers: ["Dracula"] },
  { id: 64, emojis: "🐺🌕😱", answers: ["Le Loup-Garou de Londres"] },
  { id: 65, emojis: "👻🏚️🔮", answers: ["Poltergeist"] },
  { id: 66, emojis: "😈👧✝️", answers: ["L'Exorciste"] },
  { id: 67, emojis: "🔪🎃👤", answers: ["Halloween"] },
  { id: 68, emojis: "😱🔪⛺", answers: ["Vendredi 13"] },
  { id: 69, emojis: "💭🛏️🔪", answers: ["Les Griffes de la Nuit", "Freddy"] },
  { id: 70, emojis: "🎈🤡🚢", answers: ["Ça"] },
  { id: 71, emojis: "🐊🎣🌿", answers: ["Crocodile Dundee"] },
  { id: 72, emojis: "👦🏠🎄🔫", answers: ["Maman j'ai raté l'avion"] },
  { id: 73, emojis: "🧝‍♂️🎄🎅", answers: ["Elfe"] },
  { id: 74, emojis: "🎅🏻📜✨", answers: ["Le Pôle Express"] },
  { id: 75, emojis: "👨‍🦲🥋🔫", answers: ["Hitman"] },
  { id: 76, emojis: "🏛️🗡️👑", answers: ["Gladiator"] },
  { id: 77, emojis: "🗡️⚔️🏯🇯🇵", answers: ["Le Dernier Samouraï"] },
  { id: 78, emojis: "🏹💀🌧️", answers: ["Braveheart"] },
  { id: 79, emojis: "⛵🏴‍☠️🦜", answers: ["L'Île au Trésor"] },
  { id: 80, emojis: "🤴🗡️👧", answers: ["Princess Bride"] },
  { id: 81, emojis: "🧙‍♂️🎩🕳️", answers: ["Alice au Pays des Merveilles"] },
  { id: 82, emojis: "👦🍫🏭", answers: ["Charlie et la Chocolaterie"] },
  { id: 83, emojis: "🐻🌧️🇬🇧", answers: ["Paddington"] },
  { id: 84, emojis: "🧑‍🤝‍🧑🚗💨", answers: ["Thelma et Louise"] },
  { id: 85, emojis: "💃🕺🎤", answers: ["Grease"] },
  { id: 86, emojis: "💃🕺🕺🕺🇮🇳", answers: ["Slumdog Millionaire"] },
  { id: 87, emojis: "🎤🎸👑🇬🇧", answers: ["Bohemian Rhapsody"] },
  { id: 88, emojis: "🚀👩‍🚀🔴🌌", answers: ["Seul sur Mars"] },
  { id: 89, emojis: "🌌🕳️⏰👨‍🚀", answers: ["Interstellar"] },
  { id: 90, emojis: "🚀🌍💥☄️", answers: ["Armageddon"] },
  { id: 91, emojis: "👽🛸🇺🇸🗽", answers: ["Independence Day"] },
  { id: 92, emojis: "👽💀🔫", answers: ["Alien"] },
  { id: 93, emojis: "🤖🚔🔫", answers: ["RoboCop"] },
  { id: 94, emojis: "🕵️👤💡", answers: ["Usual Suspects"] },
  { id: 95, emojis: "🧠🔍📝", answers: ["Memento"] },
  { id: 96, emojis: "🌀💭🛏️", answers: ["Inception"] },
  { id: 97, emojis: "🃏🎭💰", answers: ["Ocean's Eleven", "Ocean's 11"] },
  { id: 98, emojis: "💎🐕💰🔫", answers: ["Reservoir Dogs"] },
  { id: 99, emojis: "💉🇬🇧🏴󠁧󠁢󠁳󠁣󠁴󠁿", answers: ["Trainspotting"] },
  { id: 100, emojis: "🥊💉🏆", answers: ["Raging Bull"] },
  { id: 101, emojis: "🚕🌃🔫", answers: ["Taxi Driver"] },
  { id: 102, emojis: "🔪👨‍🍳🥩", answers: ["Sweeney Todd"] },
  { id: 103, emojis: "✂️🖐️🏰", answers: ["Edward aux mains d'argent"] },
  { id: 104, emojis: "🎠🎪🎩", answers: ["The Greatest Showman"] },
  { id: 105, emojis: "👨‍👩‍👧‍👦🌍✈️", answers: ["La Famille Addams"] },
  { id: 106, emojis: "🐶🍝❤️", answers: ["La Belle et le Clochard"] },
  { id: 107, emojis: "🦌❄️🌲", answers: ["Bambi"] },
  { id: 108, emojis: "👸💤💯", answers: ["La Belle au Bois Dormant"] },
  { id: 109, emojis: "👠💎👗🎃", answers: ["Cendrillon"] },
  { id: 110, emojis: "🏹🦊🌲", answers: ["Robin des Bois"] },
  { id: 111, emojis: "🎸💀🇲🇽👦", answers: ["Coco"] },
  { id: 112, emojis: "🔵🌳👽🏹", answers: ["Avatar"] },
  { id: 113, emojis: "🏃‍♂️🍫🦐", answers: ["Forrest Gump"] },
  { id: 114, emojis: "🇮🇹👨‍👧‍👦🔫🌹", answers: ["Le Parrain"] },
  { id: 115, emojis: "⚡🚗⏰", answers: ["Retour vers le Futur"] },
  { id: 116, emojis: "🗡️👩🐲🇨🇳", answers: ["Mulan"] },
  { id: 117, emojis: "🦍👦🌴", answers: ["Tarzan"] },
  { id: 118, emojis: "🎹💃🌃⭐", answers: ["La La Land"] },
  { id: 119, emojis: "🏠✨🦋🇨🇴", answers: ["Encanto"] },
  { id: 120, emojis: "🐉👧🛁", answers: ["Le Voyage de Chihiro"] },
  { id: 121, emojis: "🏰🌹👹🇫🇷", answers: ["Notre-Dame de Paris", "Le Bossu de Notre-Dame"] },
  { id: 122, emojis: "🎺🎷🌃🇺🇸", answers: ["Soul"] },
  { id: 123, emojis: "😢😊😡😱💭", answers: ["Vice-Versa"] },
  { id: 125, emojis: "🎲🌴🐒🦁", answers: ["Jumanji"] },
  { id: 126, emojis: "🏨❄️🪓😱", answers: ["Shining", "The Shining"] },
  { id: 127, emojis: "👻👦💀", answers: ["Sixième Sens", "Le Sixième Sens"] },
  { id: 128, emojis: "🔫👧🌱", answers: ["Léon", "Leon"] },
  { id: 129, emojis: "👧🇫🇷💚🎠", answers: ["Amélie Poulain", "Le Fabuleux Destin d'Amélie Poulain"] },
  { id: 130, emojis: "🐆🖤👑", answers: ["Black Panther"] },
  { id: 131, emojis: "🚗💥🏜️", answers: ["Mad Max", "Mad Max Fury Road"] },
  { id: 132, emojis: "🥊🧼💥", answers: ["Fight Club"] },
  { id: 133, emojis: "🦇🃏🌃💣", answers: ["The Dark Knight", "Dark Knight"] },
  { id: 134, emojis: "🧙‍♂️⏰💫👁️", answers: ["Doctor Strange"] },
  { id: 135, emojis: "🚀🌌🎸👽🌳", answers: ["Les Gardiens de la Galaxie", "Guardians of the Galaxy"] },
  { id: 136, emojis: "🐑🔇😈🍷", answers: ["Le Silence des Agneaux"] },
  { id: 137, emojis: "🌊🏄‍♀️🦈😱", answers: ["Instinct de Survie", "The Shallows"] },
  { id: 138, emojis: "👨‍🍳🔪🐟🇯🇵", answers: ["Jiro Dreams of Sushi", "Jiro"] },
  { id: 139, emojis: "🎭👯‍♀️🦢🖤", answers: ["Black Swan"] },
  { id: 140, emojis: "🏝️🔍🧠💊", answers: ["Shutter Island"] },
  { id: 141, emojis: "🦷🧚✨", answers: ["La Fée Clochette", "Tinker Bell"] },
  { id: 142, emojis: "🐼🥋🍜", answers: ["Kung Fu Panda"] },
  { id: 143, emojis: "🦓🦛🦒🏝️", answers: ["Madagascar"] },
  { id: 144, emojis: "🤖👧🔫🌸", answers: ["Alita", "Alita Battle Angel"] },
  { id: 145, emojis: "🎸🎤👨‍🎤⭐", answers: ["A Star Is Born"] },
  { id: 146, emojis: "🚂🏔️❄️🔪", answers: ["Le Crime de l'Orient-Express", "Murder on the Orient Express"] },
  { id: 147, emojis: "🧟💕🧠", answers: ["Warm Bodies"] },
  { id: 148, emojis: "🌙🐺👨", answers: ["Teen Wolf"] },
  { id: 149, emojis: "🏠👻📸", answers: ["Paranormal Activity"] },
  { id: 150, emojis: "🎪🔪😈", answers: ["Ça: Chapitre 2", "It Chapter Two"] },
  { id: 151, emojis: "🧛‍♂️💕👧🌲", answers: ["Twilight"] },
  { id: 152, emojis: "🏹🎯🔥👧", answers: ["Hunger Games"] },
  { id: 153, emojis: "📚🏃‍♂️🧪🌆", answers: ["Le Labyrinthe", "Maze Runner"] },
  { id: 154, emojis: "🚁🎖️🇺🇸✈️", answers: ["Top Gun"] },
  { id: 155, emojis: "👨‍🚀🌙🚀🇺🇸", answers: ["First Man"] },
  { id: 156, emojis: "🎹👨‍🦯🎵", answers: ["Ray"] },
  { id: 157, emojis: "👑🗣️🇬🇧", answers: ["Le Discours d'un Roi", "The King's Speech"] },
  { id: 158, emojis: "🦈🌪️😱", answers: ["Sharknado"] },
  { id: 159, emojis: "🐺🐕💉🏥", answers: ["Balto"] },
  { id: 160, emojis: "🤴⚔️🐴🏰", answers: ["Le Roi Arthur", "King Arthur"] },
  { id: 161, emojis: "🦸‍♀️⚔️🛡️🏝️", answers: ["Wonder Woman"] },
  { id: 162, emojis: "🧜‍♂️🔱🌊👑", answers: ["Aquaman"] },
  { id: 163, emojis: "💀🏊‍♂️🔫😂", answers: ["Deadpool"] },
  { id: 164, emojis: "🕷️🏠👨‍👩‍👦", answers: ["Spider-Man: Homecoming"] },
  { id: 165, emojis: "🐝🎬🍯", answers: ["Bee Movie"] },
  { id: 166, emojis: "🐢🥋🍕", answers: ["Les Tortues Ninja", "Ninja Turtles"] },
  { id: 167, emojis: "👨‍🔬⚡🦎", answers: ["The Amazing Spider-Man"] },
  { id: 168, emojis: "🎰💰🤵🍸", answers: ["Las Vegas Parano", "Fear and Loathing in Las Vegas"] },
  { id: 169, emojis: "🚌🏃‍♂️💣", answers: ["Speed"] },
  { id: 170, emojis: "🏢💥🎄", answers: ["Piège de Cristal", "Die Hard"] },
  { id: 171, emojis: "👮‍♂️🔫😎🕶️", answers: ["Men in Black", "MIB"] },
  { id: 172, emojis: "🌍⏰🦋", answers: ["L'Effet Papillon", "Butterfly Effect"] },
  { id: 173, emojis: "🎩✨🐰🪄", answers: ["Le Prestige", "The Prestige"] },
  { id: 174, emojis: "🏃‍♂️🌧️🔫🇰🇷", answers: ["Old Boy", "Oldboy"] },
  { id: 175, emojis: "🚗🤖👽", answers: ["Transformers"] },
  { id: 176, emojis: "🐉🏰🔥⚔️", answers: ["Game of Thrones", "Le Trône de Fer"] },
  { id: 177, emojis: "🧊👨‍👩‍👧‍👦🦣", answers: ["L'Âge de Glace", "Ice Age"] },
  { id: 178, emojis: "🎤👩‍🎤💜🌧️", answers: ["Purple Rain"] },
  { id: 179, emojis: "🏎️🇮🇹🏁👨‍🦳", answers: ["Ford vs Ferrari", "Le Mans 66"] },
  { id: 180, emojis: "🎻📕❤️🇮🇹", answers: ["Le Violon Rouge", "The Red Violin"] },
];

export function getRandomMovie(excludeId?: number): ServerMovie {
  let index: number;
  do {
    index = Math.floor(Math.random() * serverMovies.length);
  } while (serverMovies[index].id === excludeId && serverMovies.length > 1);
  return serverMovies[index];
}

export function getMovieById(id: number): ServerMovie | undefined {
  return serverMovies.find((m) => m.id === id);
}

export function getRandomMovieExcluding(excludeIds: Set<number>): ServerMovie {
  const available = serverMovies.filter((m) => !excludeIds.has(m.id));
  if (available.length === 0) {
    return serverMovies[Math.floor(Math.random() * serverMovies.length)];
  }
  return available[Math.floor(Math.random() * available.length)];
}
