app = "moji-server"
primary_region = "cdg"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  path = "/health"
